### ISSUE TITLE
Implement Static Code Analysis in ConverterService CI pipeline

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConverterService#3]
**Description:**
As a developer, I need to get a report about metrics that measure the quality of code. 

**Acceptance Criteria:**
- The scanning of the code should run automatically in the CI pipeline.
- The scanning should be triggered when creating a Pull Request to `main`. 
- The scanning should be triggered as well once the Pull Request has been approved.
- The reports after each scanning should be shown in our SonarQube.

**Dependency:**
This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/5

**Comment by yujrajo** [comment]
- CI pipeline now triggers SonarQube scans on Pull Requests targeting the main branch.
- CI pipeline now triggers SonarQube scans once the Pull Request has been approved.
- After an analysis, SonarQube evaluates Converter Service project against the Quality Gate conditions
- The workflow sends static code analysis and coverage reports to SonarQube server for further analysis and visualization.

**Comment by yujrajo** [comment]
Sorry Caleb, you marked the task as completed before I pushed my changes. I had to create a new Pull Request to fix this issue.
