### ISSUE TITLE
Build and Push container images in ConverterService pipeline

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConverterService#4]
**Description:**
As a developer, I want to save the artifact that contains the latest changes in the source code. A container image is going to be our artifact.

**Acceptance Criteria:**
- The pipeline should build a new container image only when running in the main branch.
- The pipeline should push the container image which has been build in a previous step only when running in the main branch.
- The container image should be stored in the Docker Registry hosted in Nexus.
- The pipeline should login the registry by using a user which doesn't have `full admin` priveleges.
- The build and push actions should happen only when the previous Quality Gate check has passed.

**Dependency:**
This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/4

**Comment by michelle-gh** [comment]
A first draft for the pipeline have been made with the following steps:
* Docker image is build
* A daemon.json file is added to be able to push to the nexus registry
* Restart docker service
* Docker login
* Tag and push the image

Env variables are being called for the docker login

**Comment by michelle-gh** [comment]
Testing to run the push image job from the pr was made. The converterservice image is sucessfuly build and push into the nexus container registry with the pipeline

The conditionals for the job to wait for the static code analysis step and run only on push to main was added
